# -*- coding: utf-8 -*-
"""linear stack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19YkSZZma_JO6YWhjdZDsdmv6YHsCKiwl
"""

# stack.py
# Implementasi Struktur Data Stack di Python
# Prinsip LIFO (Last In First Out)

class Stack:
    def __init__(self):
        self.items = []

    def is_empty(self):
        return len(self.items) == 0

    def push(self, item):
        self.items.append(item)
        print(f"Push: {item}")

    def pop(self):
        if not self.is_empty():
            popped = self.items.pop()
            print(f"Pop: {popped}")
            return popped
        else:
            print("Stack is empty! Nothing to pop.")
            return None

    def peek(self):
        if not self.is_empty():
            return self.items[-1]
        else:
            print("Stack is empty! Nothing to peek.")
            return None

    def size(self):
        return len(self.items)

    def display(self):
        print("Current Stack:", self.items)


# Contoh penggunaan Stack
if __name__ == "__main__":
    stack = Stack()

    stack.push(10)
    stack.push(20)
    stack.push(30)
    stack.display()

    stack.pop()
    stack.display()

    top_item = stack.peek()
    print(f"Peek: {top_item}")

    print(f"Stack size: {stack.size()}")